FROM python:3.11-slim

# Install curl
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY kestra-requirements.txt .
 
RUN pip install --no-cache-dir -r kestra-requirements.txt 