FROM python:3.11-slim

# Instala dependências de sistema para bibliotecas Python
RUN apt-get update && apt-get install -y build-essential curl && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY kestra-requirements.txt .
RUN pip install --no-cache-dir -r kestra-requirements.txt

# Copy all scripts and utils to the container
COPY scripts/ ./scripts/
COPY utils/ ./utils/
COPY .env .env

# Set Python path
ENV PYTHONPATH=/app 