id: 2_ai_conversation_flow
namespace: serena.production
description: "Workflow de conversação com IA v3 - Processa mensagens do lead e inicia conversa inteligente"

triggers:
  - id: converse_production_lead
    type: io.kestra.plugin.core.trigger.Webhook
    key: converse_production_lead
    description: "Recebe mensagens do lead para iniciar conversa com IA"

variables:
  # Configurações do modelo de IA
  ai_model: "gpt-4o-mini"
  max_tokens: 300
  temperature: 0.7

tasks:
  # Tarefa: Processar mensagem e iniciar conversa com IA
  - id: process-lead-message
    type: io.kestra.plugin.scripts.python.Script
    description: "Processa mensagem do lead e envia primeira resposta da IA"
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: python:3.11-slim
    
    inputFiles:
      scripts/__init__.py: |
        # Scripts package for Serena Qualifier
        # Contains AI agent tools and integrations
      scripts/ai_conversation_handler.py: "{{ read('scripts/ai_conversation_handler.py') }}"
      scripts/location_extractor.py: "{{ read('scripts/location_extractor.py') }}"
      scripts/conversation_context.py: "{{ read('scripts/conversation_context.py') }}"
      scripts/serena_api.py: "{{ read('scripts/serena_api.py') }}"
    
    # --- The following blocks are now correctly indented ---
    env:
      OPENAI_API_KEY: "{{ secret('OPENAI_API_KEY') }}"
      WHATSAPP_API_TOKEN: "{{ secret('WHATSAPP_API_TOKEN') }}"
      WHATSAPP_PHONE_NUMBER_ID: "{{ envs.whatsapp_phone_number_id }}"
      SERENA_API_TOKEN: "{{ secret('SERENA_API_TOKEN') }}"
    
    beforeCommands:
      - pip install kestra python-dotenv requests openai psycopg2-binary
    
    script: |
      # Importa o handler de conversação
      from scripts.ai_conversation_handler import handle_lead_message
      
      # Dados do trigger (mensagem do lead)
      phone_number = '{{ trigger.body.phone }}'
      message = '{{ trigger.body.message }}'
      
      # Log da mensagem recebida
      print(f"📱 Mensagem recebida de {phone_number}")
      print(f"💬 Conteúdo: {message}")
      
      # Processa mensagem e envia resposta
      result = handle_lead_message(
          phone_number=phone_number,
          message=message,
          ai_model='{{ vars.ai_model }}',
          max_tokens={{ vars.max_tokens }},
          temperature={{ vars.temperature }}
      )
      
      # Outputs para logging
      print(f"::set-output name=response_sent::{result['success']}")
      print(f"::set-output name=ai_response::{result.get('ai_response', 'N/A')}")
      print(f"::set-output name=whatsapp_message_id::{result.get('whatsapp_message_id', 'N/A')}")
      print(f"::set-output name=lead_phone::{phone_number}")

  # Log de sucesso da conversa
  - id: log-conversation-success
    type: io.kestra.plugin.core.log.Log
    description: "Registra sucesso do processamento da conversa"
    runIf: "{{ outputs['process-lead-message'].vars.response_sent == 'True' }}"
    message: |
      ✅ CONVERSA COM IA INICIADA COM SUCESSO
      =====================================
      Phone: {{ trigger.body.phone }}
      Message Received: {{ trigger.body.message }}
      AI Response: {{ outputs['process-lead-message'].vars.ai_response }}
      WhatsApp Message ID: {{ outputs['process-lead-message'].vars.whatsapp_message_id }}
      Model Used: {{ vars.ai_model }}
      Timestamp: {{ execution.startDate }}
      
      O lead deve receber a solicitação de cidade e estado para prosseguir.

  # Log de erro no processamento
  - id: log-conversation-error
    type: io.kestra.plugin.core.log.Log
    description: "Registra erro no processamento da conversa"
    runIf: "{{ outputs['process-lead-message'].vars.response_sent != 'True' }}"
    level: ERROR
    message: |
      ❌ ERRO NO PROCESSAMENTO DA CONVERSA COM IA
      ==========================================
      Phone: {{ trigger.body.phone }}
      Message Received: {{ trigger.body.message }}
      Model: {{ vars.ai_model }}
      Timestamp: {{ execution.startDate }}
      
      Verificar logs do AI handler e configurações da OpenAI API. 