id: 2_lead_reception_warmup
namespace: serena.production
description: "Deprecated: substituído por conversa_sdr"

triggers:
  - id: whatsapp_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "__deprecated__"

tasks:
  - id: noop
    type: io.kestra.plugin.core.log.Log
    message: "Este fluxo foi descontinuado. Use 'conversa_sdr'."
