id: conversa_sdr
namespace: serena.production
description: "Recebe mensagens do lead, invoca o agente de IA e envia a resposta."

triggers:
  - id: whatsapp_webhook_conversa
    type: io.kestra.plugin.core.trigger.Webhook
    key: "silvia_reception"

tasks:
  - id: extrair_dados_lead
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: python:3.11-slim
    beforeCommands:
      - pip install kestra
    script: |
      from kestra import Kestra
      import json

      trigger_body = {{ trigger.body | toJson }}

      # Estrutura do webhook do WhatsApp Cloud API
      phone = trigger_body['entry'][0]['changes'][0]['value']['messages'][0]['from']
      message_text = trigger_body['entry'][0]['changes'][0]['value']['messages'][0].get('text', {}).get('body', '')

      Kestra.outputs({
          "phone_number": phone,
          "message": message_text
      })

  - id: invocar_agente_ia
    type: io.kestra.plugin.scripts.python.Script
    description: "Executa o script ai_sdr_agent.py para processar a conversa."
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: kestra-agent:latest
    inputFiles:
      scripts/: "{{ read('scripts/') }}"
    env:
      OPENAI_API_KEY: "{{ secret('OPENAI_API_KEY') }}"
      SUPABASE_MCP_URL: "http://supabase-mcp-server:3000"
      SERENA_MCP_URL: "http://serena-mcp-server:3002"
      WHATSAPP_MCP_URL: "http://whatsapp-mcp-server:3003"
    script: |
      from kestra import Kestra
      from scripts.sdr.ai_sdr_agent import SerenaSDRAgent

      agent = SerenaSDRAgent()
      resultado = agent.run_agent(
          lead_id="{{ outputs.extrair_dados_lead.vars.phone_number }}",
          user_message="{{ outputs.extrair_dados_lead.vars.message }}"
      )

      Kestra.outputs({
          "resposta_ia": resultado.get("response", "Desculpe, não consegui processar sua mensagem.")
      })

  - id: enviar_resposta_whatsapp
    type: io.kestra.plugin.core.http.Request
    uri: "http://whatsapp-mcp-server:3003/mcp"
    method: POST
    headers:
      Content-Type: "application/json"
    body: |
      {
        "jsonrpc": "2.0",
        "id": "{{ execution.id }}",
        "method": "tools/call",
        "params": {
          "name": "sendTextMessage",
          "arguments": {
            "to": "{{ outputs.extrair_dados_lead.vars.phone_number }}",
            "message": {{ outputs.invocar_agente_ia.vars.resposta_ia | toJson }}
          }
        }
      }

