id: lead-activation-v2
namespace: serena.energia
description: "Fluxo 1: Ativação do Lead - Captura dados do formulário e envia primeira mensagem de boas-vindas"

triggers:
  - id: capture-webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: capture

tasks:
  - id: save-initial-lead
    type: io.kestra.plugin.scripts.shell.Script
    description: "Executes an external Python script to save the initial lead data to Supabase."
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: serena/kestra-python-runner:latest
      pullPolicy: NEVER
      networkMode: serena-qualifier_kestra-network
    script: |
      set -e
      export $(grep -v '^#' /app/.env | xargs)
      python /app/scripts/save_lead_to_supabase.py \
        --name "{{ trigger.body.nomeCompleto }}" \
        --phone "{{ trigger.body.whatsapp }}" \
        --email "{{ trigger.body.email | default('email@simulado.com') }}" \
        --account_value "{{ trigger.body.faixaConta | default('0') }}" \
        --client_type "{{ trigger.body.tipoCliente | default('casa') }}"

  - id: send-activation-template
    type: io.kestra.plugin.scripts.shell.Script
    description: "Envia template de ativação via Whatsapp chamando um script externo"
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: serena/kestra-python-runner:latest
      pullPolicy: NEVER
      networkMode: serena-qualifier_kestra-network
    script: |
      set -e
      export $(grep -v '^#' /app/.env | xargs)
      python /app/scripts/whatsapp_real_sender.py \
        "{{ trigger.body.whatsapp }}" \
        "{{ trigger.body.nomeCompleto }}" 